name: Build & Deploy Sitemap

on:
  push:
    branches: [ main ]    # or your default branch

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # 1) Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 2) Install dependencies
    - name: Install supabase client
      run: |
        python -m pip install --upgrade pip
        pip install supabase

    # 3) Generate sitemap
    - name: Generate sitemap
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python generate_sitemap.py

    # 4) Commit the new sitemap.xml back to repo
    - name: Commit sitemap
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add public/sitemap.xml
        git commit -m "chore: regenerate sitemap" || echo "No changes to commit"
        git push
